"""
South Sumatra Dashboard — Power BI Canvas Layout Builder
=========================================================
Automatically builds 4 report pages with full visual layout
into your existing south_sumatra_dashboard.pbix file.

INSTRUCTIONS:
1. Save and CLOSE Power BI Desktop completely before running this script
2. Install requirements: pip install chardet
3. Run: python build_pbi_layout.py
4. Open the output file: south_sumatra_dashboard_WITH_LAYOUT.pbix

Author: Generated by Claude for Arkalphaze
Date: 28 March 2026
"""

import os
import sys
import json
import shutil
import zipfile
import tempfile
import chardet
from pathlib import Path
from datetime import datetime

# ── CONFIG ────────────────────────────────────────────────────────────────────
PBIX_PATH = r"C:\Users\asus\OneDrive - Lincoln University\Life\Research\Price Spike Project\south-sumatra-price-spike-early-warning\powerbi\south_sumatra_dashboard.pbix"
OUTPUT_SUFFIX = "_WITH_LAYOUT"
# ─────────────────────────────────────────────────────────────────────────────

# Canvas size: 1280 x 720 (16:9 standard)
W, H = 1280, 720

# ── COLOUR PALETTE ────────────────────────────────────────────────────────────
RED      = "#E24B4A"
AMBER    = "#EF9F27"
GREEN    = "#639922"
BLUE     = "#378ADD"
DARK_BLUE= "#185FA5"
TEAL     = "#1D9E75"
GRAY_BG  = "#F1EFE8"
CARD_BG  = "#FFFFFF"
PAGE_BG  = "#F5F4F0"
HEADER_BG= "#0C447C"
TEXT_PRI = "#2C2C2A"
TEXT_SEC = "#5F5E5A"
BORDER   = "#D3D1C7"

# ── VISUAL BUILDER HELPERS ────────────────────────────────────────────────────

def new_id():
    """Generate a sequential visual ID string."""
    new_id._counter += 1
    return str(new_id._counter)
new_id._counter = 0


def card_visual(x, y, w, h, title, measure_table, measure_name,
                bg=CARD_BG, title_color=TEXT_SEC, value_color=TEXT_PRI,
                border_color=BORDER):
    """A KPI Card visual."""
    vid = new_id()
    config = {
        "name": vid,
        "layouts": [{"id": 0, "position": {"x": x, "y": y, "z": 0, "width": w, "height": h, "tabOrder": int(vid)}}],
        "singleVisual": {
            "visualType": "card",
            "projections": {"Values": [{"queryRef": f"{measure_table}.{measure_name}", "active": True}]},
            "prototypeQuery": {
                "Version": 2,
                "From": [{"Name": measure_table[0].lower(), "Entity": measure_table, "Type": 0}],
                "Select": [{"Measure": {"Expression": {"SourceRef": {"Source": measure_table[0].lower()}}, "Property": measure_name}, "Name": f"{measure_table}.{measure_name}"}]
            },
            "vcObjects": {
                "title": [{"properties": {"text": {"expr": {"Literal": {"Value": f"'{title}'"}}}, "show": {"expr": {"Literal": {"Value": "true"}}}, "fontColor": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{title_color}'"}}}}}, "fontSize": {"expr": {"Literal": {"Value": "'10'"}}}}}],
                "labels": [{"properties": {"color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{value_color}'"}}}}}}, "fontSize": {"expr": {"Literal": {"Value": "'20'"}}}}],
                "background": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{bg}'"}}}}}, "transparency": {"expr": {"Literal": {"Value": "'0'"}}}}}],
                "border": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{border_color}'"}}}}}, "radius": {"expr": {"Literal": {"Value": "'8'"}}}}}],
            }
        }
    }
    return _wrap_visual(config, x, y, w, h, vid)


def slicer_visual(x, y, w, h, table, column, title, orientation="horizontal"):
    """A dropdown/list slicer visual."""
    vid = new_id()
    config = {
        "name": vid,
        "singleVisual": {
            "visualType": "slicer",
            "projections": {"Values": [{"queryRef": f"{table}.{column}"}]},
            "prototypeQuery": {
                "Version": 2,
                "From": [{"Name": table[0].lower(), "Entity": table, "Type": 0}],
                "Select": [{"Column": {"Expression": {"SourceRef": {"Source": table[0].lower()}}, "Property": column}, "Name": f"{table}.{column}"}]
            },
            "vcObjects": {
                "title": [{"properties": {"text": {"expr": {"Literal": {"Value": f"'{title}'"}}}, "show": {"expr": {"Literal": {"Value": "true"}}}, "fontSize": {"expr": {"Literal": {"Value": "'10'"}}}}}],
                "background": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{CARD_BG}'"}}}}}, "transparency": {"expr": {"Literal": {"Value": "'0'"}}}}}],
                "border": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{BORDER}'"}}}}}, "radius": {"expr": {"Literal": {"Value": "'8'"}}}}}],
                "data": [{"properties": {"mode": {"expr": {"Literal": {"Value": "'Dropdown'"} if orientation == "dropdown" else {"Value": "'List'"}}}}}],
            }
        }
    }
    return _wrap_visual(config, x, y, w, h, vid)


def line_chart_visual(x, y, w, h, title, x_table, x_col,
                      y_measures, legend_table=None, legend_col=None):
    """A line chart visual."""
    vid = new_id()
    froms = [{"Name": x_table[0].lower(), "Entity": x_table, "Type": 0}]
    selects = [{"Column": {"Expression": {"SourceRef": {"Source": x_table[0].lower()}}, "Property": x_col}, "Name": f"{x_table}.{x_col}"}]
    projections = {"Category": [{"queryRef": f"{x_table}.{x_col}"}], "Y": []}
    for mt, mn in y_measures:
        if not any(f["Name"] == mt[0].lower() for f in froms):
            froms.append({"Name": mt[0].lower(), "Entity": mt, "Type": 0})
        selects.append({"Measure": {"Expression": {"SourceRef": {"Source": mt[0].lower()}}, "Property": mn}, "Name": f"{mt}.{mn}"})
        projections["Y"].append({"queryRef": f"{mt}.{mn}"})
    config = {
        "name": vid,
        "singleVisual": {
            "visualType": "lineChart",
            "projections": projections,
            "prototypeQuery": {"Version": 2, "From": froms, "Select": selects},
            "vcObjects": {
                "title": [{"properties": {"text": {"expr": {"Literal": {"Value": f"'{title}'"}}}, "show": {"expr": {"Literal": {"Value": "true"}}}, "fontSize": {"expr": {"Literal": {"Value": "'11'"}}}}}],
                "background": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{CARD_BG}'"}}}}}, "transparency": {"expr": {"Literal": {"Value": "'0'"}}}}}],
                "border": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{BORDER}'"}}}}}, "radius": {"expr": {"Literal": {"Value": "'8'"}}}}}],
            }
        }
    }
    return _wrap_visual(config, x, y, w, h, vid)


def bar_chart_visual(x, y, w, h, title, cat_table, cat_col, val_measures,
                     orientation="clusteredBar"):
    """A bar/column chart visual."""
    vid = new_id()
    froms = [{"Name": cat_table[0].lower(), "Entity": cat_table, "Type": 0}]
    selects = [{"Column": {"Expression": {"SourceRef": {"Source": cat_table[0].lower()}}, "Property": cat_col}, "Name": f"{cat_table}.{cat_col}"}]
    projections = {"Category": [{"queryRef": f"{cat_table}.{cat_col}"}], "Y": []}
    for mt, mn in val_measures:
        if not any(f["Name"] == mt[0].lower() for f in froms):
            froms.append({"Name": mt[0].lower(), "Entity": mt, "Type": 0})
        selects.append({"Measure": {"Expression": {"SourceRef": {"Source": mt[0].lower()}}, "Property": mn}, "Name": f"{mt}.{mn}"})
        projections["Y"].append({"queryRef": f"{mt}.{mn}"})
    config = {
        "name": vid,
        "singleVisual": {
            "visualType": orientation,
            "projections": projections,
            "prototypeQuery": {"Version": 2, "From": froms, "Select": selects},
            "vcObjects": {
                "title": [{"properties": {"text": {"expr": {"Literal": {"Value": f"'{title}'"}}}, "show": {"expr": {"Literal": {"Value": "true"}}}, "fontSize": {"expr": {"Literal": {"Value": "'11'"}}}}}],
                "background": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{CARD_BG}'"}}}}}, "transparency": {"expr": {"Literal": {"Value": "'0'"}}}}}],
                "border": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{BORDER}'"}}}}}, "radius": {"expr": {"Literal": {"Value": "'8'"}}}}}],
                "dataColors": [{"properties": {"color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{BLUE}'"}}}}}}}],
            }
        }
    }
    return _wrap_visual(config, x, y, w, h, vid)


def matrix_visual(x, y, w, h, title, row_table, row_col, val_measures):
    """A matrix/table visual."""
    vid = new_id()
    froms = [{"Name": row_table[0].lower(), "Entity": row_table, "Type": 0}]
    selects = [{"Column": {"Expression": {"SourceRef": {"Source": row_table[0].lower()}}, "Property": row_col}, "Name": f"{row_table}.{row_col}"}]
    projections = {"Rows": [{"queryRef": f"{row_table}.{row_col}"}], "Values": []}
    for mt, mn in val_measures:
        if not any(f["Name"] == mt[0].lower() for f in froms):
            froms.append({"Name": mt[0].lower(), "Entity": mt, "Type": 0})
        selects.append({"Measure": {"Expression": {"SourceRef": {"Source": mt[0].lower()}}, "Property": mn}, "Name": f"{mt}.{mn}"})
        projections["Values"].append({"queryRef": f"{mt}.{mn}"})
    config = {
        "name": vid,
        "singleVisual": {
            "visualType": "matrix",
            "projections": projections,
            "prototypeQuery": {"Version": 2, "From": froms, "Select": selects},
            "vcObjects": {
                "title": [{"properties": {"text": {"expr": {"Literal": {"Value": f"'{title}'"}}}, "show": {"expr": {"Literal": {"Value": "true"}}}, "fontSize": {"expr": {"Literal": {"Value": "'11'"}}}}}],
                "background": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{CARD_BG}'"}}}}}, "transparency": {"expr": {"Literal": {"Value": "'0'"}}}}}],
                "border": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{BORDER}'"}}}}}, "radius": {"expr": {"Literal": {"Value": "'8'"}}}}}],
            }
        }
    }
    return _wrap_visual(config, x, y, w, h, vid)


def text_box_visual(x, y, w, h, text, font_size=14, bold=True,
                    color=CARD_BG, bg=HEADER_BG):
    """A text box visual — used for page headers."""
    vid = new_id()
    weight = "700" if bold else "400"
    paragraphs = [{"paragraphStyle": {"textAlignment": "LEFT"},
                   "runs": [{"textStyle": {"fontWeight": weight,
                                            "fontSize": f"{font_size}pt",
                                            "color": color},
                              "value": text}]}]
    config = {
        "name": vid,
        "singleVisual": {
            "visualType": "textbox",
            "objects": {"general": [{"properties": {"paragraphs": {"expr": {"Literal": {"Value": json.dumps(paragraphs)}}}}}]},
            "vcObjects": {
                "background": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{bg}'"}}}}}, "transparency": {"expr": {"Literal": {"Value": "'0'"}}}}}],
            }
        }
    }
    return _wrap_visual(config, x, y, w, h, vid)


def shape_visual(x, y, w, h, fill=HEADER_BG, border=None):
    """A rectangle shape — used as header background/divider."""
    vid = new_id()
    config = {
        "name": vid,
        "singleVisual": {
            "visualType": "shape",
            "vcObjects": {
                "line": [{"properties": {"strokeColor": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{border or fill}'"}}}}}, "strokeWidth": {"expr": {"Literal": {"Value": "'1'"}}}}}],
                "fill": [{"properties": {"show": {"expr": {"Literal": {"Value": "true"}}}, "fillColor": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{fill}'"}}}}}, "transparency": {"expr": {"Literal": {"Value": "'0'"}}}}}],
            }
        }
    }
    return _wrap_visual(config, x, y, w, h, vid)


def _wrap_visual(config, x, y, w, h, vid):
    """Wrap a visual config into the Power BI Layout container format."""
    return {
        "x": float(x), "y": float(y), "z": float(int(vid)),
        "width": float(w), "height": float(h),
        "config": json.dumps(config),
        "filters": "[]",
        "query": "{}",
        "dataTransforms": "{}"
    }


def page_config(bg_color=PAGE_BG):
    return json.dumps({
        "relationships": [],
        "objects": {
            "background": [{"properties": {"color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{bg_color}'"}}}}}, "transparency": {"expr": {"Literal": {"Value": "'0'"}}}}}],
            "outspace": [{"properties": {"color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{bg_color}'"}}}}}, "transparency": {"expr": {"Literal": {"Value": "'0'"}}}}}]
        }
    })


# ── PAGE BUILDERS ─────────────────────────────────────────────────────────────

def build_page_1():
    """Page 1: Executive Summary"""
    pad = 12
    header_h = 52
    slicer_h = 50
    kpi_h = 72
    gap = 10

    visuals = []

    # Header bar
    visuals.append(shape_visual(0, 0, W, header_h, fill=HEADER_BG))
    visuals.append(text_box_visual(pad, 10, 500, 34,
        "South Sumatra Horticultural Price Spike Early Warning System",
        font_size=13, bold=True, color=CARD_BG, bg=HEADER_BG))
    visuals.append(text_box_visual(W - 280, 14, 270, 26,
        "Dashboard | Sumatera Selatan",
        font_size=10, bold=False, color="#85B7EB", bg=HEADER_BG))

    # Slicers row  y=62
    sy = header_h + gap
    sw = (W - 2*pad - 2*gap) // 3
    visuals.append(slicer_visual(pad,          sy, sw, slicer_h, "Calendar", "Date",      "Date Range",  "dropdown"))
    visuals.append(slicer_visual(pad+sw+gap,   sy, sw, slicer_h, "prices_dashboard", "commodity", "Commodity", "dropdown"))
    visuals.append(slicer_visual(pad+2*(sw+gap), sy, sw, slicer_h, "Calendar", "Season",    "Season",      "dropdown"))

    # Alert status card (full width)  y=124
    ay = sy + slicer_h + gap
    visuals.append(card_visual(pad, ay, W - 2*pad, kpi_h - 10,
        "Spike Alert Status", "prices_dashboard", "Spike Alert Status",
        bg=CARD_BG, value_color=RED))

    # KPI Row 1  y=196
    ky1 = ay + kpi_h
    kw = (W - 2*pad - 4*gap) // 5
    kpi_row1 = [
        ("Current Avg Price",        "prices_dashboard", "Current Avg Price",       DARK_BLUE),
        ("Historical Mean Price",    "prices_dashboard", "Historical Mean Price",   TEXT_PRI),
        ("Price Deviation %",        "prices_dashboard", "Price Deviation %",       RED),
        ("WoW Change %",             "prices_dashboard", "Week-over-Week Change %", AMBER),
        ("MoM Change %",             "prices_dashboard", "Month-over-Month Change %", AMBER),
    ]
    for i, (title, tbl, msr, col) in enumerate(kpi_row1):
        visuals.append(card_visual(pad + i*(kw+gap), ky1, kw, kpi_h, title, tbl, msr, value_color=col))

    # KPI Row 2  y=278
    ky2 = ky1 + kpi_h + gap
    kpi_row2 = [
        ("Total Spike Count",   "prices_dashboard", "Total Spike Count",   RED),
        ("Spike Frequency %",   "prices_dashboard", "Spike Frequency %",   AMBER),
        ("Avg Z-Score",         "prices_dashboard", "Avg Z-Score",         BLUE),
        ("Max Z-Score",         "prices_dashboard", "Max Z-Score",         RED),
        ("Volatility Index",    "prices_dashboard", "Volatility Index",    TEAL),
    ]
    for i, (title, tbl, msr, col) in enumerate(kpi_row2):
        visuals.append(card_visual(pad + i*(kw+gap), ky2, kw, kpi_h, title, tbl, msr, value_color=col))

    # Chart row  y=360
    cy = ky2 + kpi_h + gap
    chart_h = H - cy - pad
    chart_w_big = int((W - 2*pad - gap) * 0.62)
    chart_w_sml = W - 2*pad - gap - chart_w_big

    # Price trend line chart
    visuals.append(line_chart_visual(
        pad, cy, chart_w_big, chart_h,
        "Price Trend vs 52-Week Mean",
        "Calendar", "Date",
        [("prices_dashboard", "Current Avg Price"),
         ("prices_dashboard", "Historical Mean Price")]
    ))

    # Spike rate by commodity bar chart
    visuals.append(bar_chart_visual(
        pad + chart_w_big + gap, cy, chart_w_sml, chart_h,
        "Spike Rate by Commodity (%)",
        "prices_dashboard", "commodity",
        [("prices_dashboard", "Spike Rate by Commodity")],
        orientation="clusteredBar"
    ))

    return {
        "name": "ReportSection1",
        "displayName": "Executive Summary",
        "ordinal": 0,
        "visualContainers": visuals,
        "config": page_config(),
        "displayOption": 1,
        "width": W, "height": H, "filters": "[]"
    }


def build_page_2():
    """Page 2: Price Monitoring by Commodity & District"""
    pad = 12
    header_h = 52
    slicer_h = 50
    gap = 10

    visuals = []

    # Header
    visuals.append(shape_visual(0, 0, W, header_h, fill=TEAL))
    visuals.append(text_box_visual(pad, 12, 500, 30,
        "Price Monitoring — Commodity & District Analysis",
        font_size=13, bold=True, color=CARD_BG, bg=TEAL))

    # Slicers
    sy = header_h + gap
    sw = (W - 2*pad - 2*gap) // 3
    visuals.append(slicer_visual(pad,            sy, sw, slicer_h, "prices_dashboard", "commodity", "Commodity", "dropdown"))
    visuals.append(slicer_visual(pad+sw+gap,     sy, sw, slicer_h, "prices_dashboard", "district",  "District (Kabupaten)", "dropdown"))
    visuals.append(slicer_visual(pad+2*(sw+gap), sy, sw, slicer_h, "Calendar",          "Date",      "Date Range", "dropdown"))

    # Row 1: District bar + KPI cards  y=114
    r1y = sy + slicer_h + gap
    bar_w = int((W - 2*pad) * 0.55)
    kpi_w = (W - 2*pad - bar_w - gap) // 3
    kpi_h = 64

    visuals.append(bar_chart_visual(
        pad, r1y, bar_w, 140,
        "Average Price by District (Rp/kg)",
        "prices_dashboard", "district",
        [("prices_dashboard", "Price by District")],
        orientation="clusteredBar"
    ))

    kpis = [
        ("Highest Price District", "prices_dashboard", "Highest Price District"),
        ("Lowest Price District",  "prices_dashboard", "Lowest Price District"),
        ("Price Spread (Rp/kg)",   "prices_dashboard", "Price Spread"),
    ]
    for i, (title, tbl, msr) in enumerate(kpis):
        visuals.append(card_visual(
            pad + bar_w + gap + i*(kpi_w + gap//2), r1y,
            kpi_w, kpi_h,
            title, tbl, msr
        ))
        # district spike count below each kpi
    visuals.append(card_visual(
        pad + bar_w + gap, r1y + kpi_h + gap,
        bar_w - gap, kpi_h,
        "District Spike Count", "prices_dashboard", "District Spike Count", value_color=RED
    ))

    # Row 2: Price trend + Commodity matrix  y=290
    r2y = r1y + 150 + gap
    row2_h = H - r2y - pad
    trend_w = int((W - 2*pad - gap) * 0.6)
    matrix_w = W - 2*pad - gap - trend_w

    visuals.append(line_chart_visual(
        pad, r2y, trend_w, row2_h,
        "Price Trend by Commodity Over Time",
        "Calendar", "Date",
        [("prices_dashboard", "Current Avg Price"),
         ("prices_dashboard", "Historical Mean Price")]
    ))

    visuals.append(matrix_visual(
        pad + trend_w + gap, r2y, matrix_w, row2_h,
        "Commodity Summary",
        "prices_dashboard", "commodity",
        [("prices_dashboard", "Price by Commodity"),
         ("prices_dashboard", "Spike Rate by Commodity"),
         ("prices_dashboard", "Spike Alert Status")]
    ))

    return {
        "name": "ReportSection2",
        "displayName": "Price Monitoring",
        "ordinal": 1,
        "visualContainers": visuals,
        "config": page_config(),
        "displayOption": 1,
        "width": W, "height": H, "filters": "[]"
    }


def build_page_3():
    """Page 3: ML Model Z-Score and Spike Detection"""
    pad = 12
    header_h = 52
    slicer_h = 50
    gap = 10

    visuals = []

    # Header
    visuals.append(shape_visual(0, 0, W, header_h, fill="#533AB7"))
    visuals.append(text_box_visual(pad, 12, 500, 30,
        "Anomaly Detection — Z-Score & Spike Intelligence",
        font_size=13, bold=True, color=CARD_BG, bg="#533AB7"))

    # Slicers
    sy = header_h + gap
    sw = (W - 2*pad - gap) // 2
    visuals.append(slicer_visual(pad,        sy, sw, slicer_h, "model_scores", "commodity", "Commodity", "dropdown"))
    visuals.append(slicer_visual(pad+sw+gap, sy, sw, slicer_h, "Calendar",      "Date",      "Date Range", "dropdown"))

    # KPI Row  y=114
    ky = sy + slicer_h + gap
    kpi_h = 68
    kw = (W - 2*pad - 3*gap) // 4
    kpi_row = [
        ("Max Z-Score (All Time)", "prices_dashboard", "Max Z-Score",           RED),
        ("Avg Z-Score",            "prices_dashboard", "Avg Z-Score",           BLUE),
        ("Most Volatile Commodity","prices_dashboard", "Most Volatile Commodity",AMBER),
        ("Spike Frequency %",      "prices_dashboard", "Spike Frequency %",     RED),
    ]
    for i, (title, tbl, msr, col) in enumerate(kpi_row):
        visuals.append(card_visual(pad + i*(kw+gap), ky, kw, kpi_h, title, tbl, msr, value_color=col))

    # Z-Score trend line chart  y=192
    zy = ky + kpi_h + gap
    z_h = int((H - zy - pad - gap) * 0.52)
    visuals.append(line_chart_visual(
        pad, zy, W - 2*pad, z_h,
        "Z-Score Over Time by Commodity (Reference: ±2.0 = Spike Threshold)",
        "Calendar", "Date",
        [("prices_dashboard", "Avg Z-Score"),
         ("prices_dashboard", "Max Z-Score")]
    ))

    # Bottom row: Spike bar + Commodity rate  y=...
    by = zy + z_h + gap
    b_h = H - by - pad
    bw1 = int((W - 2*pad - gap) * 0.55)
    bw2 = W - 2*pad - gap - bw1

    visuals.append(bar_chart_visual(
        pad, by, bw1, b_h,
        "Monthly Spike Count by Commodity",
        "prices_dashboard", "commodity",
        [("prices_dashboard", "Total Spike Count")],
        orientation="clusteredColumn"
    ))

    visuals.append(matrix_visual(
        pad + bw1 + gap, by, bw2, b_h,
        "Spike Intelligence by Commodity",
        "prices_dashboard", "commodity",
        [("prices_dashboard", "Spike Rate by Commodity"),
         ("prices_dashboard", "Highest Z-Score Ever"),
         ("prices_dashboard", "Volatility Index")]
    ))

    return {
        "name": "ReportSection3",
        "displayName": "Z-Score Detection",
        "ordinal": 2,
        "visualContainers": visuals,
        "config": page_config(),
        "displayOption": 1,
        "width": W, "height": H, "filters": "[]"
    }


def build_page_4():
    """Page 4: Model Performance"""
    pad = 12
    header_h = 52
    gap = 10

    visuals = []

    # Header
    visuals.append(shape_visual(0, 0, W, header_h, fill="#0F6E56"))
    visuals.append(text_box_visual(pad, 12, 500, 30,
        "ML Model Performance — AUC, F1 & Feature Importance",
        font_size=13, bold=True, color=CARD_BG, bg="#0F6E56"))

    # Slicer
    sy = header_h + gap
    sw = int((W - 2*pad - gap) * 0.4)
    visuals.append(slicer_visual(pad,        sy, sw, 50, "model_metrics", "model",     "Model Name", "dropdown"))
    visuals.append(slicer_visual(pad+sw+gap, sy, sw, 50, "model_metrics", "condition", "Condition",  "dropdown"))

    # KPI Row  y=114
    ky = sy + 50 + gap
    kpi_h = 68
    kw = (W - 2*pad - 4*gap) // 5
    kpi_row = [
        ("Best AUC",        "model_metrics",      "Best AUC",        GREEN),
        ("Best F1 Score",   "model_metrics",      "Best F1 Score",   GREEN),
        ("Avg Precision",   "model_metrics",      "Average Precision",BLUE),
        ("Avg Recall",      "model_metrics",      "Average Recall",   BLUE),
        ("Top Feature",     "feature_importance", "Top Feature",      TEAL),
    ]
    for i, (title, tbl, msr, col) in enumerate(kpi_row):
        visuals.append(card_visual(pad + i*(kw+gap), ky, kw, kpi_h, title, tbl, msr, value_color=col))

    # Row 2: Feature importance bar + metrics matrix  y=192
    r2y = ky + kpi_h + gap
    r2h = int((H - r2y - pad - gap) * 0.52)
    fw = int((W - 2*pad - gap) * 0.45)
    mw = W - 2*pad - gap - fw

    visuals.append(bar_chart_visual(
        pad, r2y, fw, r2h,
        "Feature Importance (Ranked by Contribution)",
        "feature_importance", "feature",
        [("feature_importance", "importance")],
        orientation="clusteredBar"
    ))

    visuals.append(matrix_visual(
        pad + fw + gap, r2y, mw, r2h,
        "Model Metrics Comparison",
        "model_metrics", "model",
        [("model_metrics", "Best AUC"),
         ("model_metrics", "Best F1 Score"),
         ("model_metrics", "Average Precision"),
         ("model_metrics", "Average Recall")]
    ))

    # Row 3: Precision vs Recall bar  y=...
    r3y = r2y + r2h + gap
    r3h = H - r3y - pad

    visuals.append(bar_chart_visual(
        pad, r3y, W - 2*pad, r3h,
        "Precision vs Recall by Model & Condition",
        "model_metrics", "condition",
        [("model_metrics", "Average Precision"),
         ("model_metrics", "Average Recall")],
        orientation="clusteredColumn"
    ))

    return {
        "name": "ReportSection4",
        "displayName": "Model Performance",
        "ordinal": 3,
        "visualContainers": visuals,
        "config": page_config(),
        "displayOption": 1,
        "width": W, "height": H, "filters": "[]"
    }


# ── MAIN: PBIX PATCH ──────────────────────────────────────────────────────────

def patch_pbix(pbix_path: str):
    pbix_path = Path(pbix_path)
    if not pbix_path.exists():
        print(f"ERROR: File not found: {pbix_path}")
        sys.exit(1)

    # Backup
    backup = pbix_path.with_name(pbix_path.stem + f"_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pbix")
    shutil.copy2(pbix_path, backup)
    print(f"✅ Backup created: {backup.name}")

    # Output path
    output_path = pbix_path.with_name(pbix_path.stem + OUTPUT_SUFFIX + ".pbix")

    # Work in temp dir
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        extract_dir = tmp / "extracted"

        # Extract the zip
        with zipfile.ZipFile(pbix_path, 'r') as zf:
            zf.extractall(extract_dir)
        print("✅ Extracted .pbix")

        layout_path = extract_dir / "Report" / "Layout"
        if not layout_path.exists():
            print("ERROR: Layout file not found inside .pbix")
            sys.exit(1)

        # Detect encoding and read
        raw = layout_path.read_bytes()
        # Strip BOM if present
        if raw[:2] in (b'\xff\xfe', b'\xfe\xff'):
            raw = raw[2:]
        layout_str = raw.decode('utf-16-le')
        layout = json.loads(layout_str)
        print(f"✅ Loaded Layout JSON ({len(layout_str):,} chars)")

        # Build 4 new pages
        new_sections = [
            build_page_1(),
            build_page_2(),
            build_page_3(),
            build_page_4(),
        ]

        # Preserve existing resource packages (theme)
        layout["sections"] = new_sections
        print(f"✅ Built {len(new_sections)} pages with "
              f"{sum(len(p['visualContainers']) for p in new_sections)} total visuals")

        # Write back as UTF-16 LE without BOM
        new_layout_str = json.dumps(layout, ensure_ascii=False)
        layout_path.write_bytes(new_layout_str.encode('utf-16-le'))
        print("✅ Layout written (UTF-16 LE)")

        # Delete SecurityBindings to prevent corruption error
        sb = extract_dir / "SecurityBindings"
        if sb.exists():
            sb.unlink()
            print("✅ SecurityBindings removed")

        # Also remove SecurityBindings from Content_Types.xml
        ct_path = extract_dir / "[Content_Types].xml"
        if ct_path.exists():
            ct_text = ct_path.read_text(encoding='utf-8')
            ct_text = ct_text.replace(
                '<Override PartName="/SecurityBindings" ContentType="" />', '')
            ct_path.write_text(ct_text, encoding='utf-8')
            print("✅ Content_Types.xml updated")

        # Repackage as .pbix (must use ZIP_DEFLATED, no compression on DataModel)
        with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as zout:
            for f in sorted(extract_dir.rglob('*')):
                if f.is_file():
                    arcname = f.relative_to(extract_dir)
                    # DataModel must be stored uncompressed
                    if arcname.name == 'DataModel':
                        zout.write(f, arcname, compress_type=zipfile.ZIP_STORED)
                    else:
                        zout.write(f, arcname)

    print(f"\n🎉 SUCCESS! Output file:")
    print(f"   {output_path}")
    print(f"\nDouble-click to open in Power BI Desktop.")
    print(f"\nPages created:")
    print(f"   Page 1 — Executive Summary  (10 KPIs + 2 charts + alert card + slicers)")
    print(f"   Page 2 — Price Monitoring   (district bar + trend + commodity matrix)")
    print(f"   Page 3 — Z-Score Detection  (z-score trend + spike bar + intelligence matrix)")
    print(f"   Page 4 — Model Performance  (AUC/F1 KPIs + feature importance + metrics table)")


if __name__ == "__main__":
    print("=" * 60)
    print("  South Sumatra Dashboard — Canvas Layout Builder")
    print("=" * 60)
    patch_pbix(PBIX_PATH)
